MODEL:
  IMG_MODEL: "diva"
  TEXT_MODEL: "bigru"
  COMP_MODEL: "tirg"
  LOSS: "bbc"
  VOCAB: "clip"
  GRU:
    EMBEDDING_SIZE: 512
    NUM_UNITS: 256
    VOCABULARY_SIZE: 512
  COMP:
    EMBED_DIM: 512
    METHOD: "diva"
INPUT:
  HEIGHT: 224
  WIDTH: 224
DATASETS:
  TRAIN: ("fashionpedia_combine",)
  TEST: ("fashionpedia_comp_val", "fashionpedia_outfit_val")
SOLVER:
  IMS_PER_BATCH: 128
  NUM_EPOCHS: 40
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.00004
  WEIGHT_DECAY_BIAS: 0.00004
  CHECKPOINT_PERIOD: 20
  LRSCHEDULER: 'step'
  STEPS: (15, 25)
  WARMUP_EPOCHS: 5
TEST:
  IMS_PER_BATCH: 128
