MODEL:
  IMG_MODEL: "resnet50"
  TEXT_MODEL: "bigru"
  COMP_MODEL: "tirg"
  LOSS: "bbc"
  VOCAB: "clip"
  GRU:
    EMBEDDING_SIZE: 512
    NUM_UNITS: 1024
    VOCABULARY_SIZE: 512
  COMP:
    EMBED_DIM: 512
    METHOD: "shareproj-combine-proj"
INPUT:
  HEIGHT: 224
  WIDTH: 224
DATASETS:
#   TRAIN: ("fashionpedia_combine_val",)
#   TEST: ("fashionpedia_comp_test", "fashionpedia_outfit_test")
  TRAIN: ("fashionpedia_combine_train",)
  TEST: ("fashionpedia_comp_val", "fashionpedia_outfit_val")
SOLVER:
  IMS_PER_BATCH: 64
  NUM_EPOCHS: 40
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.00004
  WEIGHT_DECAY_BIAS: 0.00004
  CHECKPOINT_PERIOD: 20
  LRSCHEDULER: 'step'
  STEPS: (15, 25)
  WARMUP_EPOCHS: 5
TEST:
  IMS_PER_BATCH: 64
