MODEL:
  IMG_MODEL: "resnet50"
  TEXT_MODEL: "bigru"
  COMP_MODEL: "tirg"
  LOSS: "bbc"
  VOCAB: "init"
  GRU:
    EMBEDDING_SIZE: 512
    NUM_UNITS: 1024
    VOCABULARY_SIZE: 6000
  COMP:
    EMBED_DIM: 2048
INPUT:
  HEIGHT: 224
  WIDTH: 224
DATASETS:
  TRAIN: ("fashioniq_dress_train",)
  TEST: ("fashioniq_dress_val",)
SOLVER:
  IMS_PER_BATCH: 32
  NUM_EPOCHS: 80
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.00004
  WEIGHT_DECAY_BIAS: 0.00004
  CHECKPOINT_PERIOD: 40
  LRSCHEDULER: 'step'
  STEPS: (30, 50)
  WARMUP_EPOCHS: 0
TEST:
  IMS_PER_BATCH: 64
