MODEL:
  IMG_MODEL: "vqgan"
  TEXT_MODEL: "bigru"
  COMP_MODEL: "transdec"
  VOCAB: "glove"
  GRU:
    EMBEDDING_SIZE: 512
    NUM_UNITS: 1024
    VOCABULARY_SIZE: 300
  COMP:
    EMBED_DIM: 512
    METHOD: "transdec"
INPUT:
  HEIGHT: 256
  WIDTH: 256
DATASETS:
  TRAIN: ("fashioniq_dress_train", "fashioniq_shirt_train", "fashioniq_toptee_train")
  TEST: ("fashioniq_dress_val", "fashioniq_shirt_val", "fashioniq_toptee_val")
SOLVER:
  IMS_PER_BATCH: 32
  NUM_EPOCHS: 80
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.00004
  WEIGHT_DECAY_BIAS: 0.00004
  CHECKPOINT_PERIOD: 10
  LRSCHEDULER: 'step'
  STEPS: (30, 50)
  WARMUP_EPOCHS: 5
TEST:
  IMS_PER_BATCH: 64
